#!/usr/bin/env python3
"""
Convert a GIF (or any animated image format Pillow can read) into a C header
that the BMO firmware can include and play frame-by-frame.

Each frame becomes a JPEG (already decoded by face_buffer.drawJpg in firmware),
stored as a const byte array. A wrapper Animation struct holds metadata.

Usage:
  scripts/gif_to_header.py path/to/karate.gif karate
  -> writes firmware/IdleLab/animations/karate_anim.h

Then in firmware:
  #include "animations/karate_anim.h"
  play_animation(&karate_anim);
"""

import sys
import os
import argparse
from PIL import Image, ImageSequence
from io import BytesIO


def main():
    p = argparse.ArgumentParser()
    p.add_argument("input", help="path to .gif file")
    p.add_argument("name", help="C identifier (e.g. 'karate'); produces <name>_anim.h")
    p.add_argument("--max-width", type=int, default=160,
                   help="max output width in pixels (default 160)")
    p.add_argument("--max-height", type=int, default=120,
                   help="max output height in pixels (default 120)")
    p.add_argument("--cover", action="store_true",
                   help="fill the bounding box and crop overflow "
                        "(default: contain / fit within)")
    p.add_argument("--jpeg-quality", type=int, default=70,
                   help="JPEG quality 1-100 (default 70)")
    p.add_argument("--max-frames", type=int, default=40,
                   help="max number of frames (drops every Nth if more, default 40)")
    p.add_argument("--frame-ms", type=int, default=0,
                   help="ms per frame (0 = use GIF's native timing)")
    p.add_argument("--outdir", default="firmware/IdleLab/animations",
                   help="output directory")
    args = p.parse_args()

    if not args.name.replace("_", "").isalnum():
        sys.exit("name must be alphanumeric (underscores ok)")

    img = Image.open(args.input)
    frames = []
    durations = []

    # Collect all frames + native durations
    for f in ImageSequence.Iterator(img):
        frames.append(f.convert("RGB").copy())
        # Pillow gives duration in ms in info; default 100ms if missing
        d = f.info.get("duration", 100)
        durations.append(max(40, int(d)))  # min 40ms

    print(f"loaded {len(frames)} frames at {img.size}")

    # Downsample frame count if needed
    if len(frames) > args.max_frames:
        stride = len(frames) / args.max_frames
        new_frames, new_durs = [], []
        for i in range(args.max_frames):
            idx = int(i * stride)
            new_frames.append(frames[idx])
            new_durs.append(durations[idx])
        frames, durations = new_frames, new_durs
        print(f"downsampled to {len(frames)} frames")

    # Resize. Two modes:
    #  - contain (default): fit within bounding box, preserve aspect, may letterbox
    #  - cover:             fill bounding box exactly, center-crop overflow
    w, h = frames[0].size
    if args.cover:
        scale = max(args.max_width / w, args.max_height / h)
        scaled_w, scaled_h = max(1, int(w * scale)), max(1, int(h * scale))
        new_w, new_h = args.max_width, args.max_height
        resized = [f.resize((scaled_w, scaled_h), Image.LANCZOS) for f in frames]
        left = (scaled_w - new_w) // 2
        top  = (scaled_h - new_h) // 2
        frames = [f.crop((left, top, left + new_w, top + new_h)) for f in resized]
        print(f"resized+cropped (cover) to {new_w}x{new_h}")
    else:
        scale = min(args.max_width / w, args.max_height / h, 1.0)
        new_w, new_h = max(1, int(w * scale)), max(1, int(h * scale))
        if (new_w, new_h) != (w, h):
            frames = [f.resize((new_w, new_h), Image.LANCZOS) for f in frames]
            print(f"resized to {new_w}x{new_h}")

    # Average frame_ms (single value applied to all frames -- simpler firmware)
    if args.frame_ms > 0:
        avg_ms = args.frame_ms
    else:
        avg_ms = int(sum(durations) / len(durations))
    print(f"frame_ms = {avg_ms}")

    # Encode each frame as JPEG bytes
    jpeg_blobs = []
    total_bytes = 0
    for i, f in enumerate(frames):
        buf = BytesIO()
        f.save(buf, format="JPEG", quality=args.jpeg_quality, optimize=True)
        data = buf.getvalue()
        jpeg_blobs.append(data)
        total_bytes += len(data)
    print(f"total bytes: {total_bytes} ({total_bytes/1024:.1f} KB)")

    # Write header
    os.makedirs(args.outdir, exist_ok=True)
    out_path = os.path.join(args.outdir, f"{args.name}_anim.h")
    with open(out_path, "w") as out:
        out.write(f"// Generated by scripts/gif_to_header.py from {os.path.basename(args.input)}\n")
        out.write(f"// {len(jpeg_blobs)} frames, {new_w}x{new_h}, {avg_ms} ms/frame, "
                  f"{total_bytes} bytes total\n\n")
        out.write("#pragma once\n")
        out.write("#include <stdint.h>\n")
        out.write("#include <stddef.h>\n\n")
        for i, blob in enumerate(jpeg_blobs):
            out.write(f"static const uint8_t {args.name}_frame_{i}[] = {{\n  ")
            for j, byte in enumerate(blob):
                out.write(f"0x{byte:02x}, ")
                if (j + 1) % 16 == 0:
                    out.write("\n  ")
            out.write("\n};\n")
            out.write(f"static const size_t {args.name}_frame_{i}_len = {len(blob)};\n\n")

        # AnimFrame + Animation structs are defined ONCE in IdleLab.ino's
        # forward-decl block (anim_types.h equivalent). Don't redefine here
        # or multiple animation headers will collide.
        out.write(f"static const AnimFrame {args.name}_frames[] = {{\n")
        for i in range(len(jpeg_blobs)):
            out.write(f"  {{ {args.name}_frame_{i}, {args.name}_frame_{i}_len }},\n")
        out.write("};\n\n")
        out.write(f"static const Animation {args.name}_anim = {{\n")
        out.write(f"  {args.name}_frames, {len(jpeg_blobs)}, {new_w}, {new_h}, {avg_ms}\n")
        out.write("};\n")

    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
